// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-pricing-plans.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var list_pricing_plans_default = defineTool({
  name: "list_pricing_plans",
  title: "List pricing plans",
  description: "List Zypdrive electric scooter subscription plans available in Udupi/Manipal, including price, included kilometres, extra-km rate and onboarding fee.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const plans = [
      {
        id: "green",
        name: "Green",
        price_inr: 1999,
        billing_cycle: "month",
        included_km_per_day: 30,
        included_km_per_month: 750,
        extra_km_rate_inr: 4,
        onboarding_fee_inr: 2e3,
        onboarding_fee_note: "one-time, non-refundable, not charged on renewal",
        best_for: "Perfect for daily city commutes"
      },
      {
        id: "plus",
        name: "Plus",
        price_inr: 2599,
        billing_cycle: "month",
        included_km_per_day: 40,
        included_km_per_month: 1e3,
        extra_km_rate_inr: 5,
        onboarding_fee_inr: 3e3,
        onboarding_fee_note: "one-time, non-refundable, not charged on renewal",
        best_for: "More km for longer commutes",
        popular: true
      },
      {
        id: "gig",
        name: "Gig Rider",
        price_inr: 1250,
        billing_cycle: "week",
        included_km_per_day: 80,
        included_km_per_month: 2e3,
        extra_km_rate_inr: 6,
        onboarding_fee_inr: 2e3,
        refundable_deposit_inr: 3e3,
        best_for: "Built for delivery & gig workers"
      }
    ];
    return {
      content: [{ type: "text", text: JSON.stringify(plans, null, 2) }],
      structuredContent: { plans }
    };
  }
});

// src/lib/mcp/tools/list-faqs.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var FAQS = [
  { q: "Is there any downpayment?", a: "No. Just a one-time non-refundable onboarding fee starting at \u20B92,000 plus monthly rental in advance, starting at \u20B91,999/month, depending on the plan." },
  { q: "What plans do you offer?", a: "Green \u20B91,999/mo (30 km/day), Plus \u20B92,599/mo (40 km/day), Gig Rider \u20B91,250/week (80 km/day). All include free routine service for year 1 (50% off from year 2), home charging and insurance cover." },
  { q: "What if I ride more than my included km?", a: "Extra km at \u20B94/km (Green), \u20B95/km (Plus), \u20B96/km (Gig). Unused km do not carry forward." },
  { q: "Can I share the scooter?", a: "Yes, double-ride is fully supported with a single pillion (helmet mandatory)." },
  { q: "How long is the rental agreement?", a: "12 months. Renewals continue at the prevailing rental or as decided by the management; the onboarding fee is not charged again on renewal." },
  { q: "How do I charge?", a: "Plug into a regular 220V home socket. Full charge takes 3\u20134 hours and costs roughly \u20B98\u201310/day. Range is 70+ km per charge." },
  { q: "Is service included?", a: "Routine service is free for the first 12 months on all plans, including Gig Rider. From the 2nd year, 50% discount on actual service charges." },
  { q: "Do I need a Driving Licence?", a: "Yes. A valid Driving Licence and government ID (Aadhaar) are required. Scooters are RTO registered; always carry your insurance copy and wear a helmet." },
  { q: "Where do you operate?", a: "Udupi and Manipal, Karnataka." },
  { q: "How do I cancel?", a: "Give 15 days written notice. Remaining km are forfeited and the onboarding fee remains non-refundable." }
];
var list_faqs_default = defineTool2({
  name: "list_faqs",
  title: "List FAQs",
  description: "List frequently asked questions about Zypdrive e-scooter subscriptions and policies.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(FAQS, null, 2) }],
    structuredContent: { faqs: FAQS }
  })
});

// src/lib/mcp/tools/get-my-account.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_my_account_default = defineTool3({
  name: "get_my_account",
  title: "Get my Zypdrive account",
  description: "Return the signed-in Zypdrive user's basic account info (user id and email).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const account = {
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail()
    };
    return {
      content: [{ type: "text", text: JSON.stringify(account, null, 2) }],
      structuredContent: account
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "zyouzmsxnythhcsupzat";
var mcp_default = defineMcp({
  name: "zypdrive-mcp",
  title: "Zypdrive",
  version: "0.1.0",
  instructions: "Tools for Zypdrive \u2014 electric scooter subscriptions for women commuters in Udupi/Manipal. Use `list_pricing_plans` and `list_faqs` for plan/service info, and `get_my_account` to identify the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_pricing_plans_default, list_faqs_default, get_my_account_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
